// svelte-timer/src/App.svelte
<script>
  import { onDestroy } from "svelte";
  import moment from "moment";

  let seconds = 0;
  let interval;

  function start() {
    interval = setInterval(function () {
      seconds++;
    }, 1000);
  }

  function stop() {
    clearInterval(interval);
  }

  function reset() {
    stop();
    seconds = 0;
  }

  onDestroy(() => {
    stop();
  });
</script>

<main>
  <p id="timer">{new Date(seconds * 1000).toISOString().substring(11, 19)}</p>
  <button on:click={start}>Start</button>
  <button on:click={stop}>Stop</button>
  <button on:click={reset}>Reset</button>
</main>

<style>
  :root {
    text-align: center;
  }
</style>

// vue-timer/src/App.vue
<template>
  <div>
    <p id="timer">{{ formattedTime }}</p>
    <button @click="start()">Start</button>
    <button @click="stop()">Stop</button>
    <button @click="reset()">Reset</button>
  </div>
</template>

<script>
export default {
  data() {
    return {
      seconds: 0,
      timer: null,
    };
  },
  computed: {
    formattedTime() {
      return new Date(this.seconds * 1000).toISOString().substring(11, 19);
    },
  },
  beforeDestroy() {
    this.stop();
  },
  methods: {
    start() {
      this.timer = setInterval(() => {
        this.seconds++;
      }, 1000);
    },
    stop() {
      clearInterval(this.timer);
    },
    reset() {
      this.stop();
      this.seconds = 0;
    },
  },
};
</script>

<style>
:root {
  text-align: center;
}
</style>
