// svelte-timer/src/App.svelte
<script>
  import { onDestroy } from "svelte";
  import moment from "moment";

  let seconds = 0;
  let interval;

  function start() {
    interval = setInterval(function () {
      seconds++;
    }, 1000);
  }

  function stop() {
    clearInterval(interval);
  }

  function reset() {
    stop();
    seconds = 0;
  }

  onDestroy(() => {
    stop();
  });
</script>

<main>
  <p id="timer">{new Date(seconds * 1000).toISOString().substring(11, 19)}</p>
  <button on:click={start}>Start</button>
  <button on:click={stop}>Stop</button>
  <button on:click={reset}>Reset</button>
</main>

<style>
  :root {
    text-align: center;
  }
</style>

// solid-timer/src/App.jsx
import { createSignal, onCleanup } from "solid-js";

function App() {
  const [seconds, setSeconds] = createSignal(0);

  let interval;

  const start = () => {
    interval = setInterval(() => {
      setSeconds(seconds() + 1);
    }, 1000);
  };

  onCleanup(() => {
    clearInterval(interval);
  });

  return (
    <div style="text-align:center">
      <p id="timer">
        {new Date(seconds() * 1000).toISOString().substring(11, 19)}
      </p>
      <button onClick={start}>Start</button>
      <button onClick={() => clearInterval(interval)}>Stop</button>
      <button
        onClick={() => {
          clearInterval(interval);
          setSeconds(0);
        }}
      >
        Reset
      </button>
    </div>
  );
}

export default App;
